# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: BioAnth
subtitle: An open text
email: jhawks@wisc.edu
description: >- # this means to ignore newlines until "baseurl:"
  Educational material for biological anthropology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bioanth.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: johnhawks
github_username: johnhawks

# Build settings
# remote_theme: "mmistakes/so-simple-theme@3.2.0"
remote_theme: "mmistakes/minimal-mistakes@4.19.2"
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  
  
collections:
  hominins:
    output: true
    permalink: /:collection/:name
  

defaults:
# _posts
- scope:
    path: ""
    type: posts, hominins
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: false
    share: true
    related: true

minimal_mistakes_skin: "dirt" # "air", "aqua", "contrast", "dark", "default", "dirt", "neon", "mint", "plum" "sunrise"


# google_fonts:
# - name: "Source Sans Pro"
#   weights: "400,400i,700,700i"
# - name: "Lora"
#   weights: "400,400i,700,700i"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/



